spring.application.name=ms-reportes
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3307/db_reportes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

logging.level.com.duoc.quickorder=DEBUG

# JWT Configuration
jwt.secret.key=MiClaveSuperSecretaPara10Microservicios2024!
jwt.expiration.time=900000